esphome:
  name: esp32_generic
  includes:
    - include/wg_simple_component.h
    #- lib/WireGuard-ESP32-Arduino
  libraries:
    - ciniml/WireGuard-ESP32@^0.1.5

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: "Test"
  password: ""

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32 Generic Fallback Hotspot"
    password: "WdiLfSijOV6K"

captive_portal:
    

wg_simple_component:
  - lambda: |-
      auto wg_simple_component = new WgEsphome(
            const char * private_key, 
            const char * public_key, 
            IPAddress(10,0,200,7), 
            "p2psw.space", 
            11011);
      return {wg_simple_component};